### ISSUE TITLE
🐛 Bug Report: OIDC not working with Cloudflare Access

### ISSUE THREAD

**Issue by Rxyanlaw** [pocket-id/pocket-id#19]
### Reproduction steps

Make a Cloudflare Access application
Add Pocket ID as custom OIDC provider
Test the OIDC provider
Cloudflare Access throws "OIDC ERROR: Failed to exchange code for token. Make sure the client secret is correct.
undefined"

I am using Pocket ID behind Traefik and used issue #11's fix to at least get to the setup page but /api/oidc/token returns 404 not found

### Expected behavior

It should successfully exchange code for token and complete the authentication.

### Actual Behavior

![image](https://github.com/user-attachments/assets/ec8ca2c0-295f-4b49-924b-ee7d3f2d393e)

**Comment by stonith404** [comment]
I'm using Pocket ID with Cloudflare Access too so there is probably something wrong with your configuration.

Are you using the Docker installation? Can you share the Traefik configuration?

**Comment by stonith404** [comment]
Thanks. Does a POST request to `/api/oidc/token` really return 404 or did you make a GET request? Additionally, do you see any errors in the logs of the container?
